table Dim_Calendario
	lineageTag: b3bc0712-1542-45eb-aeba-166534753663

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 630f2110-1529-4798-bdb5-e8235bf279ce
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 410674aa-e4a0-45a5-a270-ac3fbcda581f
			defaultHierarchy: LocalDateTable_b4f86afe-5ffa-4016-82d4-485a295578ea.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 17c54889-7316-4c44-ba59-3dc0dc16396d
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: e7f6c662-bdac-43bc-b4f4-311d445e0ed9
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 84d7443d-bd5a-4a93-9630-8ccb892cd818
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 6ae924d6-e345-44f0-a557-0e2e2e483fcc
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 9465d7bc-265a-4dfc-8c51-bee686724253
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\josue\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

