table Fact_Ventas
	lineageTag: ed32e38e-f3a4-4513-986f-49ef507d8bd7

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 723a6fd6-9467-48a0-8407-8dbf7a86dbae
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: f538f097-795c-48e6-88ab-8d8608141af0
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: int64
		formatString: 0
		lineageTag: 364e9a6c-26cb-40b6-b167-c38ec2573c3c
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: int64
		formatString: 0
		lineageTag: d70547d6-de3c-4eae-b8af-53936cb6de41
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 14e93c23-4974-4460-8239-901dd21432df
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Vehiculo
		dataType: int64
		formatString: 0
		lineageTag: c0dbf4d4-1756-42f5-bf1e-5e8a195eced8
		summarizeBy: none
		sourceColumn: Vehiculo

		annotation SummarizationSetBy = Automatic

	column 'Costo Vehículo'
		dataType: double
		lineageTag: 568a8f08-0c28-47c8-a9dc-6e994fc3f3c0
		summarizeBy: sum
		sourceColumn: Costo Vehículo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Venta sin IGV'
		dataType: double
		lineageTag: 7d43e8ef-8794-49a5-b516-1a754e518250
		summarizeBy: sum
		sourceColumn: Precio Venta sin IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IGV
		dataType: double
		lineageTag: c5bf3471-2109-4c1f-b42e-cec38ed31b00
		summarizeBy: sum
		sourceColumn: IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sede
		dataType: int64
		formatString: 0
		lineageTag: 5334c7c7-0b98-4cc5-ae37-578a957bceeb
		summarizeBy: none
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: int64
		formatString: 0
		lineageTag: bc640740-6b99-4372-a0d7-d4d3fe23afd5
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	partition Fact_Ventas = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\josue\Downloads\VentasVehiculos.xlsx"), null, true),
				    Fact_Ventas_Table = Origen{[Item="Fact_Ventas",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Fact_Ventas_Table,{{"ID", Int64.Type}, {"datekey", Int64.Type}, {"Canal", Int64.Type}, {"Cliente", Int64.Type}, {"Segmento", type text}, {"Vehiculo", Int64.Type}, {"Costo Vehículo", type number}, {"Precio Venta sin IGV", type number}, {"IGV", type number}, {"Sede", Int64.Type}, {"Vendedor", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

